// Wire-compatible mirror of the Tachiyomi/TachiyomiSY backup models
// (app/src/main/java/eu/kanade/tachiyomi/data/backup/models/*.kt).
// Field numbers must match the Kotlin @ProtoNumber annotations exactly.
// Fields other forks add (J2K 800+, Suwayomi 9000+) survive as unknown fields.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: syncyomi/backup/v1/backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStrategy int32

const (
	UpdateStrategy_ALWAYS_UPDATE   UpdateStrategy = 0
	UpdateStrategy_ONLY_FETCH_ONCE UpdateStrategy = 1
)

// Enum value maps for UpdateStrategy.
var (
	UpdateStrategy_name = map[int32]string{
		0: "ALWAYS_UPDATE",
		1: "ONLY_FETCH_ONCE",
	}
	UpdateStrategy_value = map[string]int32{
		"ALWAYS_UPDATE":   0,
		"ONLY_FETCH_ONCE": 1,
	}
)

func (x UpdateStrategy) Enum() *UpdateStrategy {
	p := new(UpdateStrategy)
	*p = x
	return p
}

func (x UpdateStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_syncyomi_backup_v1_backup_proto_enumTypes[0].Descriptor()
}

func (UpdateStrategy) Type() protoreflect.EnumType {
	return &file_syncyomi_backup_v1_backup_proto_enumTypes[0]
}

func (x UpdateStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStrategy.Descriptor instead.
func (UpdateStrategy) EnumDescriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{0}
}

type Backup struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	BackupManga             []*BackupManga             `protobuf:"bytes,1,rep,name=backup_manga,json=backupManga,proto3" json:"backup_manga,omitempty"`
	BackupCategories        []*BackupCategory          `protobuf:"bytes,2,rep,name=backup_categories,json=backupCategories,proto3" json:"backup_categories,omitempty"`
	BackupSources           []*BackupSource            `protobuf:"bytes,101,rep,name=backup_sources,json=backupSources,proto3" json:"backup_sources,omitempty"`
	BackupPreferences       []*BackupPreference        `protobuf:"bytes,104,rep,name=backup_preferences,json=backupPreferences,proto3" json:"backup_preferences,omitempty"`
	BackupSourcePreferences []*BackupSourcePreferences `protobuf:"bytes,105,rep,name=backup_source_preferences,json=backupSourcePreferences,proto3" json:"backup_source_preferences,omitempty"`
	BackupExtensionStores   []*BackupExtensionStore    `protobuf:"bytes,106,rep,name=backup_extension_stores,json=backupExtensionStores,proto3" json:"backup_extension_stores,omitempty"`
	BackupSavedSearches     []*BackupSavedSearch       `protobuf:"bytes,600,rep,name=backup_saved_searches,json=backupSavedSearches,proto3" json:"backup_saved_searches,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Backup) GetBackupManga() []*BackupManga {
	if x != nil {
		return x.BackupManga
	}
	return nil
}

func (x *Backup) GetBackupCategories() []*BackupCategory {
	if x != nil {
		return x.BackupCategories
	}
	return nil
}

func (x *Backup) GetBackupSources() []*BackupSource {
	if x != nil {
		return x.BackupSources
	}
	return nil
}

func (x *Backup) GetBackupPreferences() []*BackupPreference {
	if x != nil {
		return x.BackupPreferences
	}
	return nil
}

func (x *Backup) GetBackupSourcePreferences() []*BackupSourcePreferences {
	if x != nil {
		return x.BackupSourcePreferences
	}
	return nil
}

func (x *Backup) GetBackupExtensionStores() []*BackupExtensionStore {
	if x != nil {
		return x.BackupExtensionStores
	}
	return nil
}

func (x *Backup) GetBackupSavedSearches() []*BackupSavedSearch {
	if x != nil {
		return x.BackupSavedSearches
	}
	return nil
}

type BackupManga struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Source       int64                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Url          string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title        string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist       *string                `protobuf:"bytes,4,opt,name=artist,proto3,oneof" json:"artist,omitempty"`
	Author       *string                `protobuf:"bytes,5,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Description  *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Genre        []string               `protobuf:"bytes,7,rep,name=genre,proto3" json:"genre,omitempty"`
	Status       int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	ThumbnailUrl *string                `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	DateAdded    int64                  `protobuf:"varint,13,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	Viewer       int32                  `protobuf:"varint,14,opt,name=viewer,proto3" json:"viewer,omitempty"`
	Chapters     []*BackupChapter       `protobuf:"bytes,16,rep,name=chapters,proto3" json:"chapters,omitempty"`
	// kotlinx writes lists of scalars unpacked
	Categories []int64           `protobuf:"varint,17,rep,name=categories,proto3" json:"categories,omitempty"`
	Tracking   []*BackupTracking `protobuf:"bytes,18,rep,name=tracking,proto3" json:"tracking,omitempty"`
	// Kotlin default is true and defaults are not encoded: absent means favorite
	Favorite           *bool            `protobuf:"varint,100,opt,name=favorite,proto3,oneof" json:"favorite,omitempty"`
	ChapterFlags       int32            `protobuf:"varint,101,opt,name=chapter_flags,json=chapterFlags,proto3" json:"chapter_flags,omitempty"`
	ViewerFlags        *int32           `protobuf:"varint,103,opt,name=viewer_flags,json=viewerFlags,proto3,oneof" json:"viewer_flags,omitempty"`
	History            []*BackupHistory `protobuf:"bytes,104,rep,name=history,proto3" json:"history,omitempty"`
	UpdateStrategy     UpdateStrategy   `protobuf:"varint,105,opt,name=update_strategy,json=updateStrategy,proto3,enum=syncyomi.backup.v1.UpdateStrategy" json:"update_strategy,omitempty"`
	LastModifiedAt     int64            `protobuf:"varint,106,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	FavoriteModifiedAt *int64           `protobuf:"varint,107,opt,name=favorite_modified_at,json=favoriteModifiedAt,proto3,oneof" json:"favorite_modified_at,omitempty"`
	ExcludedScanlators []string         `protobuf:"bytes,108,rep,name=excluded_scanlators,json=excludedScanlators,proto3" json:"excluded_scanlators,omitempty"`
	Version            int64            `protobuf:"varint,109,opt,name=version,proto3" json:"version,omitempty"`
	Notes              string           `protobuf:"bytes,110,opt,name=notes,proto3" json:"notes,omitempty"`
	Initialized        bool             `protobuf:"varint,111,opt,name=initialized,proto3" json:"initialized,omitempty"`
	Memo               []byte           `protobuf:"bytes,112,opt,name=memo,proto3" json:"memo,omitempty"`
	// TachiyomiSY
	MergedMangaReferences []*BackupMergedMangaReference `protobuf:"bytes,600,rep,name=merged_manga_references,json=mergedMangaReferences,proto3" json:"merged_manga_references,omitempty"`
	FlatMetadata          *BackupFlatMetadata           `protobuf:"bytes,601,opt,name=flat_metadata,json=flatMetadata,proto3,oneof" json:"flat_metadata,omitempty"`
	CustomStatus          int32                         `protobuf:"varint,602,opt,name=custom_status,json=customStatus,proto3" json:"custom_status,omitempty"`
	CustomThumbnailUrl    *string                       `protobuf:"bytes,603,opt,name=custom_thumbnail_url,json=customThumbnailUrl,proto3,oneof" json:"custom_thumbnail_url,omitempty"`
	// J2K
	CustomTitle       *string  `protobuf:"bytes,800,opt,name=custom_title,json=customTitle,proto3,oneof" json:"custom_title,omitempty"`
	CustomArtist      *string  `protobuf:"bytes,801,opt,name=custom_artist,json=customArtist,proto3,oneof" json:"custom_artist,omitempty"`
	CustomAuthor      *string  `protobuf:"bytes,802,opt,name=custom_author,json=customAuthor,proto3,oneof" json:"custom_author,omitempty"`
	CustomDescription *string  `protobuf:"bytes,804,opt,name=custom_description,json=customDescription,proto3,oneof" json:"custom_description,omitempty"`
	CustomGenre       []string `protobuf:"bytes,805,rep,name=custom_genre,json=customGenre,proto3" json:"custom_genre,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackupManga) Reset() {
	*x = BackupManga{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupManga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupManga) ProtoMessage() {}

func (x *BackupManga) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupManga.ProtoReflect.Descriptor instead.
func (*BackupManga) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupManga) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *BackupManga) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupManga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupManga) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *BackupManga) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *BackupManga) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BackupManga) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *BackupManga) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BackupManga) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *BackupManga) GetDateAdded() int64 {
	if x != nil {
		return x.DateAdded
	}
	return 0
}

func (x *BackupManga) GetViewer() int32 {
	if x != nil {
		return x.Viewer
	}
	return 0
}

func (x *BackupManga) GetChapters() []*BackupChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *BackupManga) GetCategories() []int64 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *BackupManga) GetTracking() []*BackupTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

func (x *BackupManga) GetFavorite() bool {
	if x != nil && x.Favorite != nil {
		return *x.Favorite
	}
	return false
}

func (x *BackupManga) GetChapterFlags() int32 {
	if x != nil {
		return x.ChapterFlags
	}
	return 0
}

func (x *BackupManga) GetViewerFlags() int32 {
	if x != nil && x.ViewerFlags != nil {
		return *x.ViewerFlags
	}
	return 0
}

func (x *BackupManga) GetHistory() []*BackupHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *BackupManga) GetUpdateStrategy() UpdateStrategy {
	if x != nil {
		return x.UpdateStrategy
	}
	return UpdateStrategy_ALWAYS_UPDATE
}

func (x *BackupManga) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

func (x *BackupManga) GetFavoriteModifiedAt() int64 {
	if x != nil && x.FavoriteModifiedAt != nil {
		return *x.FavoriteModifiedAt
	}
	return 0
}

func (x *BackupManga) GetExcludedScanlators() []string {
	if x != nil {
		return x.ExcludedScanlators
	}
	return nil
}

func (x *BackupManga) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackupManga) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *BackupManga) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *BackupManga) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *BackupManga) GetMergedMangaReferences() []*BackupMergedMangaReference {
	if x != nil {
		return x.MergedMangaReferences
	}
	return nil
}

func (x *BackupManga) GetFlatMetadata() *BackupFlatMetadata {
	if x != nil {
		return x.FlatMetadata
	}
	return nil
}

func (x *BackupManga) GetCustomStatus() int32 {
	if x != nil {
		return x.CustomStatus
	}
	return 0
}

func (x *BackupManga) GetCustomThumbnailUrl() string {
	if x != nil && x.CustomThumbnailUrl != nil {
		return *x.CustomThumbnailUrl
	}
	return ""
}

func (x *BackupManga) GetCustomTitle() string {
	if x != nil && x.CustomTitle != nil {
		return *x.CustomTitle
	}
	return ""
}

func (x *BackupManga) GetCustomArtist() string {
	if x != nil && x.CustomArtist != nil {
		return *x.CustomArtist
	}
	return ""
}

func (x *BackupManga) GetCustomAuthor() string {
	if x != nil && x.CustomAuthor != nil {
		return *x.CustomAuthor
	}
	return ""
}

func (x *BackupManga) GetCustomDescription() string {
	if x != nil && x.CustomDescription != nil {
		return *x.CustomDescription
	}
	return ""
}

func (x *BackupManga) GetCustomGenre() []string {
	if x != nil {
		return x.CustomGenre
	}
	return nil
}

type BackupChapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scanlator      *string                `protobuf:"bytes,3,opt,name=scanlator,proto3,oneof" json:"scanlator,omitempty"`
	Read           bool                   `protobuf:"varint,4,opt,name=read,proto3" json:"read,omitempty"`
	Bookmark       bool                   `protobuf:"varint,5,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	LastPageRead   int64                  `protobuf:"varint,6,opt,name=last_page_read,json=lastPageRead,proto3" json:"last_page_read,omitempty"`
	DateFetch      int64                  `protobuf:"varint,7,opt,name=date_fetch,json=dateFetch,proto3" json:"date_fetch,omitempty"`
	DateUpload     int64                  `protobuf:"varint,8,opt,name=date_upload,json=dateUpload,proto3" json:"date_upload,omitempty"`
	ChapterNumber  float32                `protobuf:"fixed32,9,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	SourceOrder    int64                  `protobuf:"varint,10,opt,name=source_order,json=sourceOrder,proto3" json:"source_order,omitempty"`
	LastModifiedAt int64                  `protobuf:"varint,11,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	Version        int64                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	Memo           []byte                 `protobuf:"bytes,13,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupChapter) Reset() {
	*x = BackupChapter{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChapter) ProtoMessage() {}

func (x *BackupChapter) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChapter.ProtoReflect.Descriptor instead.
func (*BackupChapter) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupChapter) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupChapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupChapter) GetScanlator() string {
	if x != nil && x.Scanlator != nil {
		return *x.Scanlator
	}
	return ""
}

func (x *BackupChapter) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *BackupChapter) GetBookmark() bool {
	if x != nil {
		return x.Bookmark
	}
	return false
}

func (x *BackupChapter) GetLastPageRead() int64 {
	if x != nil {
		return x.LastPageRead
	}
	return 0
}

func (x *BackupChapter) GetDateFetch() int64 {
	if x != nil {
		return x.DateFetch
	}
	return 0
}

func (x *BackupChapter) GetDateUpload() int64 {
	if x != nil {
		return x.DateUpload
	}
	return 0
}

func (x *BackupChapter) GetChapterNumber() float32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *BackupChapter) GetSourceOrder() int64 {
	if x != nil {
		return x.SourceOrder
	}
	return 0
}

func (x *BackupChapter) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

func (x *BackupChapter) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackupChapter) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

type BackupCategory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Order          int64                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Id             int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Flags          int64                  `protobuf:"varint,100,opt,name=flags,proto3" json:"flags,omitempty"`
	Version        int64                  `protobuf:"varint,601,opt,name=version,proto3" json:"version,omitempty"`
	Uid            int64                  `protobuf:"varint,602,opt,name=uid,proto3" json:"uid,omitempty"`
	LastModifiedAt int64                  `protobuf:"varint,603,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupCategory) Reset() {
	*x = BackupCategory{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCategory) ProtoMessage() {}

func (x *BackupCategory) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCategory.ProtoReflect.Descriptor instead.
func (*BackupCategory) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupCategory) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *BackupCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackupCategory) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *BackupCategory) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackupCategory) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BackupCategory) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

type BackupSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSource) Reset() {
	*x = BackupSource{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSource) ProtoMessage() {}

func (x *BackupSource) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSource.ProtoReflect.Descriptor instead.
func (*BackupSource) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupSource) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type BackupHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	LastRead      int64                  `protobuf:"varint,2,opt,name=last_read,json=lastRead,proto3" json:"last_read,omitempty"`
	ReadDuration  int64                  `protobuf:"varint,3,opt,name=read_duration,json=readDuration,proto3" json:"read_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupHistory) Reset() {
	*x = BackupHistory{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupHistory) ProtoMessage() {}

func (x *BackupHistory) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupHistory.ProtoReflect.Descriptor instead.
func (*BackupHistory) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *BackupHistory) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupHistory) GetLastRead() int64 {
	if x != nil {
		return x.LastRead
	}
	return 0
}

func (x *BackupHistory) GetReadDuration() int64 {
	if x != nil {
		return x.ReadDuration
	}
	return 0
}

type BackupTracking struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SyncId              int32                  `protobuf:"varint,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	LibraryId           int64                  `protobuf:"varint,2,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	MediaIdInt          int32                  `protobuf:"varint,3,opt,name=media_id_int,json=mediaIdInt,proto3" json:"media_id_int,omitempty"`
	TrackingUrl         string                 `protobuf:"bytes,4,opt,name=tracking_url,json=trackingUrl,proto3" json:"tracking_url,omitempty"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	LastChapterRead     float32                `protobuf:"fixed32,6,opt,name=last_chapter_read,json=lastChapterRead,proto3" json:"last_chapter_read,omitempty"`
	TotalChapters       int32                  `protobuf:"varint,7,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Score               float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	Status              int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	StartedReadingDate  int64                  `protobuf:"varint,10,opt,name=started_reading_date,json=startedReadingDate,proto3" json:"started_reading_date,omitempty"`
	FinishedReadingDate int64                  `protobuf:"varint,11,opt,name=finished_reading_date,json=finishedReadingDate,proto3" json:"finished_reading_date,omitempty"`
	Private             bool                   `protobuf:"varint,12,opt,name=private,proto3" json:"private,omitempty"`
	MediaId             int64                  `protobuf:"varint,100,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupTracking) Reset() {
	*x = BackupTracking{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupTracking) ProtoMessage() {}

func (x *BackupTracking) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupTracking.ProtoReflect.Descriptor instead.
func (*BackupTracking) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupTracking) GetSyncId() int32 {
	if x != nil {
		return x.SyncId
	}
	return 0
}

func (x *BackupTracking) GetLibraryId() int64 {
	if x != nil {
		return x.LibraryId
	}
	return 0
}

func (x *BackupTracking) GetMediaIdInt() int32 {
	if x != nil {
		return x.MediaIdInt
	}
	return 0
}

func (x *BackupTracking) GetTrackingUrl() string {
	if x != nil {
		return x.TrackingUrl
	}
	return ""
}

func (x *BackupTracking) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupTracking) GetLastChapterRead() float32 {
	if x != nil {
		return x.LastChapterRead
	}
	return 0
}

func (x *BackupTracking) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *BackupTracking) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BackupTracking) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BackupTracking) GetStartedReadingDate() int64 {
	if x != nil {
		return x.StartedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetFinishedReadingDate() int64 {
	if x != nil {
		return x.FinishedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *BackupTracking) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type BackupSavedSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	FilterList    string                 `protobuf:"bytes,3,opt,name=filter_list,json=filterList,proto3" json:"filter_list,omitempty"`
	Source        int64                  `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSavedSearch) Reset() {
	*x = BackupSavedSearch{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSavedSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSavedSearch) ProtoMessage() {}

func (x *BackupSavedSearch) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSavedSearch.ProtoReflect.Descriptor instead.
func (*BackupSavedSearch) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupSavedSearch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupSavedSearch) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *BackupSavedSearch) GetFilterList() string {
	if x != nil {
		return x.FilterList
	}
	return ""
}

func (x *BackupSavedSearch) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

// kotlinx polymorphic encoding of the sealed PreferenceValue: {1: serial name, 2: value message}.
// The value is kept opaque; the server never interprets preferences.
type PreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceValue) Reset() {
	*x = PreferenceValue{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceValue) ProtoMessage() {}

func (x *PreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceValue.ProtoReflect.Descriptor instead.
func (*PreferenceValue) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{8}
}

func (x *PreferenceValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PreferenceValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BackupPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *PreferenceValue       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupPreference) Reset() {
	*x = BackupPreference{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupPreference) ProtoMessage() {}

func (x *BackupPreference) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupPreference.ProtoReflect.Descriptor instead.
func (*BackupPreference) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{9}
}

func (x *BackupPreference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BackupPreference) GetValue() *PreferenceValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type BackupSourcePreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceKey     string                 `protobuf:"bytes,1,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	Prefs         []*BackupPreference    `protobuf:"bytes,2,rep,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSourcePreferences) Reset() {
	*x = BackupSourcePreferences{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSourcePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSourcePreferences) ProtoMessage() {}

func (x *BackupSourcePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSourcePreferences.ProtoReflect.Descriptor instead.
func (*BackupSourcePreferences) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{10}
}

func (x *BackupSourcePreferences) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *BackupSourcePreferences) GetPrefs() []*BackupPreference {
	if x != nil {
		return x.Prefs
	}
	return nil
}

type BackupExtensionStore struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IndexUrl         string                 `protobuf:"bytes,1,opt,name=index_url,json=indexUrl,proto3" json:"index_url,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BadgeLabel       *string                `protobuf:"bytes,3,opt,name=badge_label,json=badgeLabel,proto3,oneof" json:"badge_label,omitempty"`
	ContactWebsite   string                 `protobuf:"bytes,4,opt,name=contact_website,json=contactWebsite,proto3" json:"contact_website,omitempty"`
	SigningKey       string                 `protobuf:"bytes,5,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	ContactDiscord   *string                `protobuf:"bytes,6,opt,name=contact_discord,json=contactDiscord,proto3,oneof" json:"contact_discord,omitempty"`
	IsLegacy         *bool                  `protobuf:"varint,7,opt,name=is_legacy,json=isLegacy,proto3,oneof" json:"is_legacy,omitempty"`
	ExtensionListUrl *string                `protobuf:"bytes,8,opt,name=extension_list_url,json=extensionListUrl,proto3,oneof" json:"extension_list_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackupExtensionStore) Reset() {
	*x = BackupExtensionStore{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupExtensionStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupExtensionStore) ProtoMessage() {}

func (x *BackupExtensionStore) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupExtensionStore.ProtoReflect.Descriptor instead.
func (*BackupExtensionStore) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{11}
}

func (x *BackupExtensionStore) GetIndexUrl() string {
	if x != nil {
		return x.IndexUrl
	}
	return ""
}

func (x *BackupExtensionStore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupExtensionStore) GetBadgeLabel() string {
	if x != nil && x.BadgeLabel != nil {
		return *x.BadgeLabel
	}
	return ""
}

func (x *BackupExtensionStore) GetContactWebsite() string {
	if x != nil {
		return x.ContactWebsite
	}
	return ""
}

func (x *BackupExtensionStore) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

func (x *BackupExtensionStore) GetContactDiscord() string {
	if x != nil && x.ContactDiscord != nil {
		return *x.ContactDiscord
	}
	return ""
}

func (x *BackupExtensionStore) GetIsLegacy() bool {
	if x != nil && x.IsLegacy != nil {
		return *x.IsLegacy
	}
	return false
}

func (x *BackupExtensionStore) GetExtensionListUrl() string {
	if x != nil && x.ExtensionListUrl != nil {
		return *x.ExtensionListUrl
	}
	return ""
}

type BackupMergedMangaReference struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsInfoManga       bool                   `protobuf:"varint,1,opt,name=is_info_manga,json=isInfoManga,proto3" json:"is_info_manga,omitempty"`
	GetChapterUpdates bool                   `protobuf:"varint,2,opt,name=get_chapter_updates,json=getChapterUpdates,proto3" json:"get_chapter_updates,omitempty"`
	ChapterSortMode   int32                  `protobuf:"varint,3,opt,name=chapter_sort_mode,json=chapterSortMode,proto3" json:"chapter_sort_mode,omitempty"`
	ChapterPriority   int32                  `protobuf:"varint,4,opt,name=chapter_priority,json=chapterPriority,proto3" json:"chapter_priority,omitempty"`
	DownloadChapters  bool                   `protobuf:"varint,5,opt,name=download_chapters,json=downloadChapters,proto3" json:"download_chapters,omitempty"`
	MergeUrl          string                 `protobuf:"bytes,6,opt,name=merge_url,json=mergeUrl,proto3" json:"merge_url,omitempty"`
	MangaUrl          string                 `protobuf:"bytes,7,opt,name=manga_url,json=mangaUrl,proto3" json:"manga_url,omitempty"`
	MangaSourceId     int64                  `protobuf:"varint,8,opt,name=manga_source_id,json=mangaSourceId,proto3" json:"manga_source_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackupMergedMangaReference) Reset() {
	*x = BackupMergedMangaReference{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupMergedMangaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupMergedMangaReference) ProtoMessage() {}

func (x *BackupMergedMangaReference) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupMergedMangaReference.ProtoReflect.Descriptor instead.
func (*BackupMergedMangaReference) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{12}
}

func (x *BackupMergedMangaReference) GetIsInfoManga() bool {
	if x != nil {
		return x.IsInfoManga
	}
	return false
}

func (x *BackupMergedMangaReference) GetGetChapterUpdates() bool {
	if x != nil {
		return x.GetChapterUpdates
	}
	return false
}

func (x *BackupMergedMangaReference) GetChapterSortMode() int32 {
	if x != nil {
		return x.ChapterSortMode
	}
	return 0
}

func (x *BackupMergedMangaReference) GetChapterPriority() int32 {
	if x != nil {
		return x.ChapterPriority
	}
	return 0
}

func (x *BackupMergedMangaReference) GetDownloadChapters() bool {
	if x != nil {
		return x.DownloadChapters
	}
	return false
}

func (x *BackupMergedMangaReference) GetMergeUrl() string {
	if x != nil {
		return x.MergeUrl
	}
	return ""
}

func (x *BackupMergedMangaReference) GetMangaUrl() string {
	if x != nil {
		return x.MangaUrl
	}
	return ""
}

func (x *BackupMergedMangaReference) GetMangaSourceId() int64 {
	if x != nil {
		return x.MangaSourceId
	}
	return 0
}

type BackupFlatMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SearchMetadata *BackupSearchMetadata  `protobuf:"bytes,1,opt,name=search_metadata,json=searchMetadata,proto3" json:"search_metadata,omitempty"`
	SearchTags     []*BackupSearchTag     `protobuf:"bytes,2,rep,name=search_tags,json=searchTags,proto3" json:"search_tags,omitempty"`
	SearchTitles   []*BackupSearchTitle   `protobuf:"bytes,3,rep,name=search_titles,json=searchTitles,proto3" json:"search_titles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupFlatMetadata) Reset() {
	*x = BackupFlatMetadata{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupFlatMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupFlatMetadata) ProtoMessage() {}

func (x *BackupFlatMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupFlatMetadata.ProtoReflect.Descriptor instead.
func (*BackupFlatMetadata) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{13}
}

func (x *BackupFlatMetadata) GetSearchMetadata() *BackupSearchMetadata {
	if x != nil {
		return x.SearchMetadata
	}
	return nil
}

func (x *BackupFlatMetadata) GetSearchTags() []*BackupSearchTag {
	if x != nil {
		return x.SearchTags
	}
	return nil
}

func (x *BackupFlatMetadata) GetSearchTitles() []*BackupSearchTitle {
	if x != nil {
		return x.SearchTitles
	}
	return nil
}

type BackupSearchMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uploader      *string                `protobuf:"bytes,1,opt,name=uploader,proto3,oneof" json:"uploader,omitempty"`
	Extra         string                 `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	IndexedExtra  *string                `protobuf:"bytes,3,opt,name=indexed_extra,json=indexedExtra,proto3,oneof" json:"indexed_extra,omitempty"`
	ExtraVersion  int32                  `protobuf:"varint,4,opt,name=extra_version,json=extraVersion,proto3" json:"extra_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSearchMetadata) Reset() {
	*x = BackupSearchMetadata{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSearchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSearchMetadata) ProtoMessage() {}

func (x *BackupSearchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSearchMetadata.ProtoReflect.Descriptor instead.
func (*BackupSearchMetadata) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{14}
}

func (x *BackupSearchMetadata) GetUploader() string {
	if x != nil && x.Uploader != nil {
		return *x.Uploader
	}
	return ""
}

func (x *BackupSearchMetadata) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *BackupSearchMetadata) GetIndexedExtra() string {
	if x != nil && x.IndexedExtra != nil {
		return *x.IndexedExtra
	}
	return ""
}

func (x *BackupSearchMetadata) GetExtraVersion() int32 {
	if x != nil {
		return x.ExtraVersion
	}
	return 0
}

type BackupSearchTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSearchTag) Reset() {
	*x = BackupSearchTag{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSearchTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSearchTag) ProtoMessage() {}

func (x *BackupSearchTag) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSearchTag.ProtoReflect.Descriptor instead.
func (*BackupSearchTag) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{15}
}

func (x *BackupSearchTag) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *BackupSearchTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupSearchTag) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type BackupSearchTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSearchTitle) Reset() {
	*x = BackupSearchTitle{}
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSearchTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSearchTitle) ProtoMessage() {}

func (x *BackupSearchTitle) ProtoReflect() protoreflect.Message {
	mi := &file_syncyomi_backup_v1_backup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSearchTitle.ProtoReflect.Descriptor instead.
func (*BackupSearchTitle) Descriptor() ([]byte, []int) {
	return file_syncyomi_backup_v1_backup_proto_rawDescGZIP(), []int{16}
}

func (x *BackupSearchTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupSearchTitle) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_syncyomi_backup_v1_backup_proto protoreflect.FileDescriptor

const file_syncyomi_backup_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x1fsyncyomi/backup/v1/backup.proto\x12\x12syncyomi.backup.v1\"\xe2\x04\n" +
	"\x06Backup\x12B\n" +
	"\fbackup_manga\x18\x01 \x03(\v2\x1f.syncyomi.backup.v1.BackupMangaR\vbackupManga\x12O\n" +
	"\x11backup_categories\x18\x02 \x03(\v2\".syncyomi.backup.v1.BackupCategoryR\x10backupCategories\x12G\n" +
	"\x0ebackup_sources\x18e \x03(\v2 .syncyomi.backup.v1.BackupSourceR\rbackupSources\x12S\n" +
	"\x12backup_preferences\x18h \x03(\v2$.syncyomi.backup.v1.BackupPreferenceR\x11backupPreferences\x12g\n" +
	"\x19backup_source_preferences\x18i \x03(\v2+.syncyomi.backup.v1.BackupSourcePreferencesR\x17backupSourcePreferences\x12`\n" +
	"\x17backup_extension_stores\x18j \x03(\v2(.syncyomi.backup.v1.BackupExtensionStoreR\x15backupExtensionStores\x12Z\n" +
	"\x15backup_saved_searches\x18\xd8\x04 \x03(\v2%.syncyomi.backup.v1.BackupSavedSearchR\x13backupSavedSearches\"\xa8\r\n" +
	"\vBackupManga\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x03R\x06source\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\x06artist\x18\x04 \x01(\tH\x00R\x06artist\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x05 \x01(\tH\x01R\x06author\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05genre\x18\a \x03(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12(\n" +
	"\rthumbnail_url\x18\t \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"date_added\x18\r \x01(\x03R\tdateAdded\x12\x16\n" +
	"\x06viewer\x18\x0e \x01(\x05R\x06viewer\x12=\n" +
	"\bchapters\x18\x10 \x03(\v2!.syncyomi.backup.v1.BackupChapterR\bchapters\x12\"\n" +
	"\n" +
	"categories\x18\x11 \x03(\x03B\x02\x10\x00R\n" +
	"categories\x12>\n" +
	"\btracking\x18\x12 \x03(\v2\".syncyomi.backup.v1.BackupTrackingR\btracking\x12\x1f\n" +
	"\bfavorite\x18d \x01(\bH\x04R\bfavorite\x88\x01\x01\x12#\n" +
	"\rchapter_flags\x18e \x01(\x05R\fchapterFlags\x12&\n" +
	"\fviewer_flags\x18g \x01(\x05H\x05R\vviewerFlags\x88\x01\x01\x12;\n" +
	"\ahistory\x18h \x03(\v2!.syncyomi.backup.v1.BackupHistoryR\ahistory\x12K\n" +
	"\x0fupdate_strategy\x18i \x01(\x0e2\".syncyomi.backup.v1.UpdateStrategyR\x0eupdateStrategy\x12(\n" +
	"\x10last_modified_at\x18j \x01(\x03R\x0elastModifiedAt\x125\n" +
	"\x14favorite_modified_at\x18k \x01(\x03H\x06R\x12favoriteModifiedAt\x88\x01\x01\x12/\n" +
	"\x13excluded_scanlators\x18l \x03(\tR\x12excludedScanlators\x12\x18\n" +
	"\aversion\x18m \x01(\x03R\aversion\x12\x14\n" +
	"\x05notes\x18n \x01(\tR\x05notes\x12 \n" +
	"\vinitialized\x18o \x01(\bR\vinitialized\x12\x12\n" +
	"\x04memo\x18p \x01(\fR\x04memo\x12g\n" +
	"\x17merged_manga_references\x18\xd8\x04 \x03(\v2..syncyomi.backup.v1.BackupMergedMangaReferenceR\x15mergedMangaReferences\x12Q\n" +
	"\rflat_metadata\x18\xd9\x04 \x01(\v2&.syncyomi.backup.v1.BackupFlatMetadataH\aR\fflatMetadata\x88\x01\x01\x12$\n" +
	"\rcustom_status\x18\xda\x04 \x01(\x05R\fcustomStatus\x126\n" +
	"\x14custom_thumbnail_url\x18\xdb\x04 \x01(\tH\bR\x12customThumbnailUrl\x88\x01\x01\x12'\n" +
	"\fcustom_title\x18\xa0\x06 \x01(\tH\tR\vcustomTitle\x88\x01\x01\x12)\n" +
	"\rcustom_artist\x18\xa1\x06 \x01(\tH\n" +
	"R\fcustomArtist\x88\x01\x01\x12)\n" +
	"\rcustom_author\x18\xa2\x06 \x01(\tH\vR\fcustomAuthor\x88\x01\x01\x123\n" +
	"\x12custom_description\x18\xa4\x06 \x01(\tH\fR\x11customDescription\x88\x01\x01\x12\"\n" +
	"\fcustom_genre\x18\xa5\x06 \x03(\tR\vcustomGenreB\t\n" +
	"\a_artistB\t\n" +
	"\a_authorB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_thumbnail_urlB\v\n" +
	"\t_favoriteB\x0f\n" +
	"\r_viewer_flagsB\x17\n" +
	"\x15_favorite_modified_atB\x10\n" +
	"\x0e_flat_metadataB\x17\n" +
	"\x15_custom_thumbnail_urlB\x0f\n" +
	"\r_custom_titleB\x10\n" +
	"\x0e_custom_artistB\x10\n" +
	"\x0e_custom_authorB\x15\n" +
	"\x13_custom_description\"\x9e\x03\n" +
	"\rBackupChapter\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tscanlator\x18\x03 \x01(\tH\x00R\tscanlator\x88\x01\x01\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12\x1a\n" +
	"\bbookmark\x18\x05 \x01(\bR\bbookmark\x12$\n" +
	"\x0elast_page_read\x18\x06 \x01(\x03R\flastPageRead\x12\x1d\n" +
	"\n" +
	"date_fetch\x18\a \x01(\x03R\tdateFetch\x12\x1f\n" +
	"\vdate_upload\x18\b \x01(\x03R\n" +
	"dateUpload\x12%\n" +
	"\x0echapter_number\x18\t \x01(\x02R\rchapterNumber\x12!\n" +
	"\fsource_order\x18\n" +
	" \x01(\x03R\vsourceOrder\x12(\n" +
	"\x10last_modified_at\x18\v \x01(\x03R\x0elastModifiedAt\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversion\x12\x12\n" +
	"\x04memo\x18\r \x01(\fR\x04memoB\f\n" +
	"\n" +
	"_scanlator\"\xb9\x01\n" +
	"\x0eBackupCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05flags\x18d \x01(\x03R\x05flags\x12\x19\n" +
	"\aversion\x18\xd9\x04 \x01(\x03R\aversion\x12\x11\n" +
	"\x03uid\x18\xda\x04 \x01(\x03R\x03uid\x12)\n" +
	"\x10last_modified_at\x18\xdb\x04 \x01(\x03R\x0elastModifiedAt\"?\n" +
	"\fBackupSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x03R\bsourceId\"c\n" +
	"\rBackupHistory\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tlast_read\x18\x02 \x01(\x03R\blastRead\x12#\n" +
	"\rread_duration\x18\x03 \x01(\x03R\freadDuration\"\xbf\x03\n" +
	"\x0eBackupTracking\x12\x17\n" +
	"\async_id\x18\x01 \x01(\x05R\x06syncId\x12\x1d\n" +
	"\n" +
	"library_id\x18\x02 \x01(\x03R\tlibraryId\x12 \n" +
	"\fmedia_id_int\x18\x03 \x01(\x05R\n" +
	"mediaIdInt\x12!\n" +
	"\ftracking_url\x18\x04 \x01(\tR\vtrackingUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12*\n" +
	"\x11last_chapter_read\x18\x06 \x01(\x02R\x0flastChapterRead\x12%\n" +
	"\x0etotal_chapters\x18\a \x01(\x05R\rtotalChapters\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x120\n" +
	"\x14started_reading_date\x18\n" +
	" \x01(\x03R\x12startedReadingDate\x122\n" +
	"\x15finished_reading_date\x18\v \x01(\x03R\x13finishedReadingDate\x12\x18\n" +
	"\aprivate\x18\f \x01(\bR\aprivate\x12\x19\n" +
	"\bmedia_id\x18d \x01(\x03R\amediaId\"v\n" +
	"\x11BackupSavedSearch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1f\n" +
	"\vfilter_list\x18\x03 \x01(\tR\n" +
	"filterList\x12\x16\n" +
	"\x06source\x18\x04 \x01(\x03R\x06source\";\n" +
	"\x0fPreferenceValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"_\n" +
	"\x10BackupPreference\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.syncyomi.backup.v1.PreferenceValueR\x05value\"t\n" +
	"\x17BackupSourcePreferences\x12\x1d\n" +
	"\n" +
	"source_key\x18\x01 \x01(\tR\tsourceKey\x12:\n" +
	"\x05prefs\x18\x02 \x03(\v2$.syncyomi.backup.v1.BackupPreferenceR\x05prefs\"\x83\x03\n" +
	"\x14BackupExtensionStore\x12\x1b\n" +
	"\tindex_url\x18\x01 \x01(\tR\bindexUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\vbadge_label\x18\x03 \x01(\tH\x00R\n" +
	"badgeLabel\x88\x01\x01\x12'\n" +
	"\x0fcontact_website\x18\x04 \x01(\tR\x0econtactWebsite\x12\x1f\n" +
	"\vsigning_key\x18\x05 \x01(\tR\n" +
	"signingKey\x12,\n" +
	"\x0fcontact_discord\x18\x06 \x01(\tH\x01R\x0econtactDiscord\x88\x01\x01\x12 \n" +
	"\tis_legacy\x18\a \x01(\bH\x02R\bisLegacy\x88\x01\x01\x121\n" +
	"\x12extension_list_url\x18\b \x01(\tH\x03R\x10extensionListUrl\x88\x01\x01B\x0e\n" +
	"\f_badge_labelB\x12\n" +
	"\x10_contact_discordB\f\n" +
	"\n" +
	"_is_legacyB\x15\n" +
	"\x13_extension_list_url\"\xd6\x02\n" +
	"\x1aBackupMergedMangaReference\x12\"\n" +
	"\ris_info_manga\x18\x01 \x01(\bR\visInfoManga\x12.\n" +
	"\x13get_chapter_updates\x18\x02 \x01(\bR\x11getChapterUpdates\x12*\n" +
	"\x11chapter_sort_mode\x18\x03 \x01(\x05R\x0fchapterSortMode\x12)\n" +
	"\x10chapter_priority\x18\x04 \x01(\x05R\x0fchapterPriority\x12+\n" +
	"\x11download_chapters\x18\x05 \x01(\bR\x10downloadChapters\x12\x1b\n" +
	"\tmerge_url\x18\x06 \x01(\tR\bmergeUrl\x12\x1b\n" +
	"\tmanga_url\x18\a \x01(\tR\bmangaUrl\x12&\n" +
	"\x0fmanga_source_id\x18\b \x01(\x03R\rmangaSourceId\"\xf9\x01\n" +
	"\x12BackupFlatMetadata\x12Q\n" +
	"\x0fsearch_metadata\x18\x01 \x01(\v2(.syncyomi.backup.v1.BackupSearchMetadataR\x0esearchMetadata\x12D\n" +
	"\vsearch_tags\x18\x02 \x03(\v2#.syncyomi.backup.v1.BackupSearchTagR\n" +
	"searchTags\x12J\n" +
	"\rsearch_titles\x18\x03 \x03(\v2%.syncyomi.backup.v1.BackupSearchTitleR\fsearchTitles\"\xbb\x01\n" +
	"\x14BackupSearchMetadata\x12\x1f\n" +
	"\buploader\x18\x01 \x01(\tH\x00R\buploader\x88\x01\x01\x12\x14\n" +
	"\x05extra\x18\x02 \x01(\tR\x05extra\x12(\n" +
	"\rindexed_extra\x18\x03 \x01(\tH\x01R\findexedExtra\x88\x01\x01\x12#\n" +
	"\rextra_version\x18\x04 \x01(\x05R\fextraVersionB\v\n" +
	"\t_uploaderB\x10\n" +
	"\x0e_indexed_extra\"j\n" +
	"\x0fBackupSearchTag\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04typeB\f\n" +
	"\n" +
	"_namespace\"=\n" +
	"\x11BackupSearchTitle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type*8\n" +
	"\x0eUpdateStrategy\x12\x11\n" +
	"\rALWAYS_UPDATE\x10\x00\x12\x13\n" +
	"\x0fONLY_FETCH_ONCE\x10\x01B4Z2github.com/SyncYomi/SyncYomi/internal/backup/pb;pbb\x06proto3"

var (
	file_syncyomi_backup_v1_backup_proto_rawDescOnce sync.Once
	file_syncyomi_backup_v1_backup_proto_rawDescData []byte
)

func file_syncyomi_backup_v1_backup_proto_rawDescGZIP() []byte {
	file_syncyomi_backup_v1_backup_proto_rawDescOnce.Do(func() {
		file_syncyomi_backup_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syncyomi_backup_v1_backup_proto_rawDesc), len(file_syncyomi_backup_v1_backup_proto_rawDesc)))
	})
	return file_syncyomi_backup_v1_backup_proto_rawDescData
}

var file_syncyomi_backup_v1_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_syncyomi_backup_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_syncyomi_backup_v1_backup_proto_goTypes = []any{
	(UpdateStrategy)(0),                // 0: syncyomi.backup.v1.UpdateStrategy
	(*Backup)(nil),                     // 1: syncyomi.backup.v1.Backup
	(*BackupManga)(nil),                // 2: syncyomi.backup.v1.BackupManga
	(*BackupChapter)(nil),              // 3: syncyomi.backup.v1.BackupChapter
	(*BackupCategory)(nil),             // 4: syncyomi.backup.v1.BackupCategory
	(*BackupSource)(nil),               // 5: syncyomi.backup.v1.BackupSource
	(*BackupHistory)(nil),              // 6: syncyomi.backup.v1.BackupHistory
	(*BackupTracking)(nil),             // 7: syncyomi.backup.v1.BackupTracking
	(*BackupSavedSearch)(nil),          // 8: syncyomi.backup.v1.BackupSavedSearch
	(*PreferenceValue)(nil),            // 9: syncyomi.backup.v1.PreferenceValue
	(*BackupPreference)(nil),           // 10: syncyomi.backup.v1.BackupPreference
	(*BackupSourcePreferences)(nil),    // 11: syncyomi.backup.v1.BackupSourcePreferences
	(*BackupExtensionStore)(nil),       // 12: syncyomi.backup.v1.BackupExtensionStore
	(*BackupMergedMangaReference)(nil), // 13: syncyomi.backup.v1.BackupMergedMangaReference
	(*BackupFlatMetadata)(nil),         // 14: syncyomi.backup.v1.BackupFlatMetadata
	(*BackupSearchMetadata)(nil),       // 15: syncyomi.backup.v1.BackupSearchMetadata
	(*BackupSearchTag)(nil),            // 16: syncyomi.backup.v1.BackupSearchTag
	(*BackupSearchTitle)(nil),          // 17: syncyomi.backup.v1.BackupSearchTitle
}
var file_syncyomi_backup_v1_backup_proto_depIdxs = []int32{
	2,  // 0: syncyomi.backup.v1.Backup.backup_manga:type_name -> syncyomi.backup.v1.BackupManga
	4,  // 1: syncyomi.backup.v1.Backup.backup_categories:type_name -> syncyomi.backup.v1.BackupCategory
	5,  // 2: syncyomi.backup.v1.Backup.backup_sources:type_name -> syncyomi.backup.v1.BackupSource
	10, // 3: syncyomi.backup.v1.Backup.backup_preferences:type_name -> syncyomi.backup.v1.BackupPreference
	11, // 4: syncyomi.backup.v1.Backup.backup_source_preferences:type_name -> syncyomi.backup.v1.BackupSourcePreferences
	12, // 5: syncyomi.backup.v1.Backup.backup_extension_stores:type_name -> syncyomi.backup.v1.BackupExtensionStore
	8,  // 6: syncyomi.backup.v1.Backup.backup_saved_searches:type_name -> syncyomi.backup.v1.BackupSavedSearch
	3,  // 7: syncyomi.backup.v1.BackupManga.chapters:type_name -> syncyomi.backup.v1.BackupChapter
	7,  // 8: syncyomi.backup.v1.BackupManga.tracking:type_name -> syncyomi.backup.v1.BackupTracking
	6,  // 9: syncyomi.backup.v1.BackupManga.history:type_name -> syncyomi.backup.v1.BackupHistory
	0,  // 10: syncyomi.backup.v1.BackupManga.update_strategy:type_name -> syncyomi.backup.v1.UpdateStrategy
	13, // 11: syncyomi.backup.v1.BackupManga.merged_manga_references:type_name -> syncyomi.backup.v1.BackupMergedMangaReference
	14, // 12: syncyomi.backup.v1.BackupManga.flat_metadata:type_name -> syncyomi.backup.v1.BackupFlatMetadata
	9,  // 13: syncyomi.backup.v1.BackupPreference.value:type_name -> syncyomi.backup.v1.PreferenceValue
	10, // 14: syncyomi.backup.v1.BackupSourcePreferences.prefs:type_name -> syncyomi.backup.v1.BackupPreference
	15, // 15: syncyomi.backup.v1.BackupFlatMetadata.search_metadata:type_name -> syncyomi.backup.v1.BackupSearchMetadata
	16, // 16: syncyomi.backup.v1.BackupFlatMetadata.search_tags:type_name -> syncyomi.backup.v1.BackupSearchTag
	17, // 17: syncyomi.backup.v1.BackupFlatMetadata.search_titles:type_name -> syncyomi.backup.v1.BackupSearchTitle
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_syncyomi_backup_v1_backup_proto_init() }
func file_syncyomi_backup_v1_backup_proto_init() {
	if File_syncyomi_backup_v1_backup_proto != nil {
		return
	}
	file_syncyomi_backup_v1_backup_proto_msgTypes[1].OneofWrappers = []any{}
	file_syncyomi_backup_v1_backup_proto_msgTypes[2].OneofWrappers = []any{}
	file_syncyomi_backup_v1_backup_proto_msgTypes[11].OneofWrappers = []any{}
	file_syncyomi_backup_v1_backup_proto_msgTypes[14].OneofWrappers = []any{}
	file_syncyomi_backup_v1_backup_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syncyomi_backup_v1_backup_proto_rawDesc), len(file_syncyomi_backup_v1_backup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_syncyomi_backup_v1_backup_proto_goTypes,
		DependencyIndexes: file_syncyomi_backup_v1_backup_proto_depIdxs,
		EnumInfos:         file_syncyomi_backup_v1_backup_proto_enumTypes,
		MessageInfos:      file_syncyomi_backup_v1_backup_proto_msgTypes,
	}.Build()
	File_syncyomi_backup_v1_backup_proto = out.File
	file_syncyomi_backup_v1_backup_proto_goTypes = nil
	file_syncyomi_backup_v1_backup_proto_depIdxs = nil
}
